### ISSUE TITLE
Login & Register Page

### ISSUE THREAD

**Issue by junuthapa011** [junuthapa011/E-commerceApp-next.js#1]
Create a Login page & Register page with Next.js.

Estimated time: 2 days

**Comment by junuthapa011** [comment]
![Image](https://github.com/junuthapa011/E-commerceApp-next.js/assets/133033600/6d5668b7-6546-4eec-8f8a-cb4369457b7d)

**Comment by junuthapa011** [comment]
![Image](https://github.com/junuthapa011/E-commerceApp-next.js/assets/133033600/a78d95a0-3959-4351-b6cc-7d8bbf805273)


![Image](https://github.com/junuthapa011/E-commerceApp-next.js/assets/133033600/523db4c1-df9e-4500-9f56-a2d083b2bf2e)


![Image](https://github.com/junuthapa011/E-commerceApp-next.js/assets/133033600/8abb42ba-4405-49b8-951a-28cf355e78e2)




![Image](https://github.com/junuthapa011/E-commerceApp-next.js/assets/133033600/dcc7103e-8479-47a2-8537-4fbcf670b9c0)


![Image](https://github.com/junuthapa011/E-commerceApp-next.js/assets/133033600/fa67f5b9-54a2-45a3-ae3e-e1b13f925d5f)




![Image](https://github.com/junuthapa011/E-commerceApp-next.js/assets/133033600/c4d1f60b-dfe8-4897-9af1-7230529fa823)

**Comment by yogeshtakeo** [comment]
Looks Great Junu, 
Barbie Theme 👌
