### ISSUE TITLE
Intiation Phase

### ISSUE THREAD

**Issue by yogeshtakeo** [junuthapa011/E-commerceApp-next.js#2]
Design components, and pages on Figma.

Estimated time: 1 day

**Comment by junuthapa011** [comment]
![Image](https://github.com/junuthapa011/E-commerceApp-next.js/assets/133033600/8daa6bf9-ecfe-4398-8307-8e84e98ffcce)

**Comment by yogeshtakeo** [comment]
love it

**Comment by junuthapa011** [comment]
![Image](https://github.com/junuthapa011/E-commerceApp-next.js/assets/133033600/cc8ecfef-9e41-43cd-abca-7b5562cafaf1)



![Image](https://github.com/junuthapa011/E-commerceApp-next.js/assets/133033600/6f5e6ba0-ca50-4927-a9d5-9fdbe34d25a2)



![Image](https://github.com/junuthapa011/E-commerceApp-next.js/assets/133033600/fa1f7a99-76bd-4f0e-9f0b-94ccdcf9060f)

**Comment by yogeshtakeo** [comment]
Looks great Junu loved it ❤️
